version: 2.1
jobs:
  upload-to-pip:
    docker:
      - image: cimg/python:3.11.1
    steps:
      - checkout
      - run:
          name: "Installing Twine"
          command: pip install -U twine
      - run:
          name: "Installing Build"
          command: pip install build
      - run:
          name: "Building Distribution"
          command: python -m build
      - run:
          name: "Uploading to Pip"
          command: |
            twine upload --repository testpypi dist/*
            twine upload dist/*

workflows:
  build-workflow:
    jobs:
      - upload-to-pip
