version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/dist
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Testing S Compiler/Interpreter
          command: echo Here Be Pytest

  deploy:
    executor: python/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - python/install-packages:
          pkg-manager: pip
      - run: pip install twine && twine upload dist/*

workflows:
  test_my_app:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
#          filters:
#            branches:
#              only: master