version: 2.1
jobs:
  upload-to-pip:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Upload to Pip"
          command: |
            echo Hello, World!

workflows:
  build-workflow:
    jobs:
      - upload-to-pip
