version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Building Distribution
          command: |
            pip install build
            python -m build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - attach_workspace:
          at: ~/project
      - run:
          name: Installing S Interpreter
          command: pip install .
      - run:
          name: Installing Pytest
          command: pip install pytest
      - run:
          name: Testing S Compiler/Interpreter
          command: python -m pytest .

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Installing Twine
          command: pip install twine
      - run:
          name: Uploading To Test Pypi
          command: twine upload --skip-existing --repository testpypi dist/*
      - run:
          name: Uploading To Pypi
          command: twine upload --skip-existing dist/*

workflows:
  ci:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master